### ISSUE TITLE
Deprecated warning when calling `load`

### ISSUE THREAD

**Issue by fishix10** [queryverse/ExcelFiles.jl#30]
Called `load(file, sheetName)` and get the following warning on 1.1.0:

    ┌ Warning: `getindex(o::PyObject, s::Symbol)` is deprecated in favor of dot overloading (`getproperty`) so elements should now be accessed as e.g. `o.s` instead of `o[:s]`.
    │   caller = getiterator(::ExcelFiles.ExcelFile) at ExcelFiles.jl:115
    └ @ ExcelFiles C:\Users\artto\.julia\packages\ExcelFiles\rnqJh\src\ExcelFiles.jl:115

**Comment by davidanthoff** [comment]
Thanks! Should be fixed in the latest release: https://github.com/JuliaLang/METADATA.jl/pull/21999
