### ISSUE TITLE
Update deps

### ISSUE THREAD

**Issue by felipenoris** [queryverse/ExcelFiles.jl#32]
I would recommend update deps for XLSX v0.5 .
This would be a good time to switch to the new Project.toml thing for queryverse packages.

Let me know if you need help with this. I could send PRs for that, but maybe you want to do it on your own.

**Comment by davidanthoff** [comment]
Alright, I migrated every package in Queryverse over to Project.toml, including this one here :)

Was XLSX 0.5 a breaking release in some way? Or would we expect that ExcelFiles should be working with XLSX 0.5 and with older versions? In the latter case, we don't need to update anything here, right?

**Comment by felipenoris** [comment]
Yes, it is non-breaking regarding the API. But I dropped support for Julia v0.7 .

**Comment by davidanthoff** [comment]
I also dropped 0.7 support. So I think we can just leave everything as is now and folks should just get the latest version of things automatically, right?

**Comment by felipenoris** [comment]
Yes. You specified `XLSX = "≥ 0.4.1"` in the project file. Whenever a user executes `Pkg.update()`, user's manifest file will be updated with the latest XLSX version, if that satisfies other dependencies rules.

**Comment by davidanthoff** [comment]
I’m actually not happy with these bounds at all, I’d much prefer to use standard semver here. But I think that is really only practical once packages have a major version of 1. So at least for queryverse I’m just releasing 1.0 for everything now. It would be great if one could somehow say that any XLXS version larger than X but smaller than 1.0.0 would be ok...

**Comment by felipenoris** [comment]
The way I'm working right now for XLSX, you could set `XLSX = "^0.5.0"` which targets version numbers in the range `[0.5.0, 0.6.0)`.

Once I tag a v0.6 version, there will be some breaking change comparing to v0.5 . This is equivalent to consider 0.5 to 0.6 a MAJOR change, and 0.5.0 to 0.5.1 a MINOR or PATCH change, regarding semver.

I think I'll take quite some time to reach v1.0 on this one. This is very subjective thing, but I find that other packages work that way as well.

**Comment by felipenoris** [comment]
Also, if you take a look at `Project.toml` at XLSX.jl, you'll find that I don't set any restrictions on dependencies. I leave to the user `Manifect.toml` file to be the safety net. The tradeoff is that I don't micromanage dependencies, but I must check regularly for broken tests after a package update.

**Comment by davidanthoff** [comment]
I wish there was just clear guidelines of what packages should do in this new world. I'd just like to do whatever the recommended julia way is, and not even think about it :)

**Comment by davidanthoff** [comment]
But in any case, I think with the clear strategy that you have for XLSX, I'll do the thing you suggest above.

**Comment by felipenoris** [comment]
Well, I prefer to keep my comments to myself after all the trouble I got into in that discourse thread. :smile: 

But feel free to hint me if you need anything in another direction!
